---

- name: install logrotate
  package:
    name: logrotate
    state: present
#  when:
#    logrotate_scripts is defined and logrotate_scripts|length > 0

- name: setup logrotate.conf scripts
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf

- name: setup logrotate.d scripts
  template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}/{{ item.name }}"
  loop:
    "{{ logrotate_scripts }}"
  when:
    logrotate_scripts is defined

- name: Ensure systemd service unit is stopped and disabled
  service:
    name: logrotate.service
    state: stopped
    enabled: false
  ignore_errors: true
  when: ( ansible_service_mgr is defined and ansible_service_mgr | lower == "systemd" )
