---

- include: prepare.yaml
  become: true
  tags:
    - logrotate_prepare
    - logrotate_configure

- include: install.yaml
  become: true
  tags:
    - logrotate_install

- include: configure.yaml
  become: true
  tags:
    - logrotate_configure

- name: handle systemd
  include_tasks: systemd.yaml
  tags:
    - logrotate_systemd

- name: create cron job
  include_tasks: cron.yaml
  tags:
    - logrotate_cron

...
