---

- name: update package cache
  ansible.builtin.package:
    update_cache: true

- name: merge logrotate global configuration between defaults and custom
  ansible.builtin.set_fact:
    logrotate_global: "{{ logrotate_defaults_global | combine(logrotate_global, recursive=True) }}"

...
